### ISSUE TITLE
USB-Tethering disabled with newer phones

### ISSUE THREAD

**Issue by flavianz** [MathisLav/internetce#16]
I saw that an issue like this has already been created and fixed with a commit a few weeks back, but it still won't work for me...

I've tried it with a Pixel 7a with Android 14 and a Galaxy A71 with Android 13 (and both with USB-C) and I can't enable USB-Tethering for either of them. The phones are not the problem, when connected to a PC, the tethering works just fine.

Thanks for any help!

**Comment by Wistaro** [comment]
It seems that there is an issue on the reading of the USB descriptor. 
https://tiplanet.org/forum/viewtopic.php?f=12&t=24140&start=100

The behavior is the same on my phone (Android 7).

**Comment by flavianz** [comment]
Yeah ik, have you found any solution to this?

**Comment by MathisLav** [comment]
Hello,

Thank you for your message. Would it be possible that you send me a PCAP file of what wireshark captures when you enable the USB tethering between your phone and you computer? The steps of how to capture USB are described there : https://wiki.wireshark.org/CaptureSetup/USB

It will allow me to precisely know what USB descriptor your phone is sending, and adapt InternetCE consequently. If you don't want to upload it publicly (there will be your phone model, but nothing more) you can mail it to me to `github [at] mlavigne [dot] fr [dot] nf`

**Comment by flavianz** [comment]
Hi, thanks for looking into it.
Heres the capture I made, I hope I did everything the rigth way

[tethering-capture.zip](https://github.com/MathisLav/internetce/files/14184838/tethering-capture.zip)

**Comment by MathisLav** [comment]
So, I looked at what you sent, and I'm confused: it seems that you phone sends a bluetooth internet tethering descriptor, instead of an USB descriptor, as the screenshot shows:

![image](https://github.com/MathisLav/internetce/assets/14053445/e89905b0-926d-4235-88d1-42ddf2cb4d11)

But overlooking this field and considering your phone is a valid USB tethering device may work anyway. I'll send you a test program as soon as I can, to see if it is the case.

Otherwise, if it does not work, I'm afraid that I won't be able to support your phone, as it may require to support a new network protocol (we will see).

**Comment by MathisLav** [comment]
My bad I just looked at the wrong descriptor (but strange anyway that you phone sends something like this?), you have a valid USB tethering descriptor that is not supported yet by the lib, but that I can easily support. I'll send you a test program as soon as possible.

**Comment by flavianz** [comment]
Perfect! 
Thanks so much, I love the project
