### ISSUE TITLE
Calculator crash, phone didn't detect it

### ISSUE THREAD

**Issue by Tom-GARNIER** [MathisLav/internetce#17]
Hello,
I had a problem with InternetCE: when I open the internet program on my calculator, either (with my program, it's only the minimal.c example) the screen is white, and I need to press a key to exit (the first time it reset my calculator), either (with the program sent in another issue by @MathisLav ), the screen display "Web connecting ...", and I couldn't do something as long I reset.
I twice case, my phone didn't detect the USB (to use USB Modem sharing) (I have a samsung on android 11), and my computer neither (I didn't know how to do usb tethering on windows.
Can you help me?
Thanks You

**Comment by MathisLav** [comment]
Hello, can you detail your link between the calculator and the phone?

Briefly, USB connections always have a host (that leads the communication) and a device (that cannot send messages to the host, unless it is asked to). And the protocol determines which peripheral is what thanks to the shape of the USB connector you plug in each device.

So if you connect the wrong USB connector, it may not work as expected.

**Comment by Tom-GARNIER** [comment]
Hello,
I use the cable to charge the calculator and transfert data between computer.
To connect to my phone, I use and usb-c adaptador to usb A
I tried with another cable (used with camera) and another usb-c adaptador (usb-hub). Doesn’t working...
I would try to use my computer as network,  but I don't know how to share Internet over usb on computer.
I want to be sure it will work before to buy a cable.
Twice devices (calculator and phone) are fully charge.
Thanks-you.


(Sorry for my bad English)

**Comment by MathisLav** [comment]
No need to talk in 3 different platforms: I let you check my message on Ti-Planet : https://tiplanet.org/forum/viewtopic.php?t=24140&p=275438

I'll post here a summary of what it'd been said once the problem is fixed.

**Comment by MathisLav** [comment]
Alright so the issues lied on the Mini USB type plugged into the calculator (Mini USB B instead of Mini USB A).

One must pay attention at the USB type that they plug on 1 side and the other. The calculator MUST be plugged to a mini USB A cable so that it acts as the host of the communication.

An example of adapter that can be used in this context is the following : https://www.amazon.fr/Adaptateur-USB-Femelle-Mini-femelle/dp/B00XBU014Q

You'll then have to plug the A endpoint of your Ti Ti cable into the calculator, the other side on the adapter, and plug the adapter to your phone charging cable.
